//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIteration3_Dotnet_Assignments.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MindtreeMVCExerciseEntities : DbContext
    {
        public MindtreeMVCExerciseEntities()
            : base("name=MindtreeMVCExerciseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_blog> tbl_blog { get; set; }
        public virtual DbSet<tbl_comment> tbl_comment { get; set; }
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_faculty> tbl_faculty { get; set; }
        public virtual DbSet<tbl_task> tbl_task { get; set; }
    }
}
