//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIteration3_Dotnet_Assignments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faculty
    {
        public tbl_faculty()
        {
            this.tbl_task = new HashSet<tbl_task>();
        }
    
        public int facultyid { get; set; }
        public string faculty_name { get; set; }
    
        public virtual ICollection<tbl_task> tbl_task { get; set; }
    }
}
