//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIteration3_Dotnet_Assignments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blog
    {
        public tbl_blog()
        {
            this.tbl_comment = new HashSet<tbl_comment>();
        }
    
        public int blogid { get; set; }
        public string blogname { get; set; }
        public string description { get; set; }
        public string body { get; set; }
    
        public virtual ICollection<tbl_comment> tbl_comment { get; set; }
    }
}
