//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIteration3_Dotnet_Assignments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comment
    {
        public int commentid { get; set; }
        public string comment { get; set; }
        public Nullable<int> blogid { get; set; }
    
        public virtual tbl_blog tbl_blog { get; set; }
    }
}
