// <auto-generated />
namespace Astra.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResourceTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResourceTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201307231935513_resourcetypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
