// <auto-generated />
namespace Astra.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReportFramework2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReportFramework2));
        
        string IMigrationMetadata.Id
        {
            get { return "201307122012098_ReportFramework2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
